---
    environment: production
    chdir: /root/dminion
    address: 0.0.0.0
    user: root
    group: root
    port: 4567
    pid: /root/dminion/thin.pid
    rackup: /root/dminion/config.ru
    log: /root/dminion/thin.log
    max_conns: 100
    timeout: 30
    max_persistent_conns: 100
    daemonize: true
